### ISSUE TITLE
hsc2hs checking not working

### ISSUE THREAD

**Issue by ysangkok** [UU-ComputerScience/uhc#82] opened 2016-08-18 12:40 UTC
I get this error during compilation:

```
mkdir -p build/101/ehclib/base/System && \
if grep -q 'HSC2HS_EXTRA'  ;\
then \
   sed -e 's/^HSC2HS_EXTRA=.*$/HSC2HS_EXTRA=/' <  > build/101/ehclib/hsc2hs && chmod +x build/101/ehclib/hsc2hs && \
         build/101/ehclib/hsc2hs -v --output=build/101/ehclib/base/System/CPUTime.hs \
              --include=HsFFI.h \
              --cc=/usr/bin/gcc \
         -D__UHC__=1010905 \
         -D__UHC_TARGET_BC__ \
         -D__UHC_TARGET__=bc \
         -I/tmp/uhc-master/EHC/install/101/include/bc/ \
         -I/tmp/uhc-master/EHC/install/101/shared/include/ \
	      -Iehclib/uhcbase/include/ -Iehclib/base/include/ -Iehclib/array/include/ -Iehclib/filepath/include/ -Iehclib/old-locale/include/ -Iehclib/old-time/include/ -Iehclib/unix/include/ -Iehclib/directory/include/ -Iehclib/random/include/ \
         -Iinstall/101/lib/pkg/uhcbase-1.1.9.5/101/bc/plain/include -Iinstall/101/lib/pkg/base-3.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/array-1.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/filepath-1.1.0.4/101/bc/plain/include -Iinstall/101/lib/pkg/old-locale-1.0.0.2/101/bc/plain/include -Iinstall/101/lib/pkg/old-time-1.0.0.4/101/bc/plain/include -Iinstall/101/lib/pkg/unix-1.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/directory-1.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/random-1.0.0.2/101/bc/plain/include \
	   ehclib/base/System/CPUTime.hsc ; \
else \
       -v --output=build/101/ehclib/base/System/CPUTime.hs --no-compile --include=HsFFI.h ehclib/base/System/CPUTime.hsc && \
   /usr/bin/gcc -D__UHC__=1010905 \
      -D__UHC_TARGET_BC__ -D__UHC_TARGET__=bc \
      -I/tmp/uhc-master/EHC/install/101/include/bc/ \
      -I/tmp/uhc-master/EHC/install/101/shared/include/ \
	    -Iehclib/uhcbase/include/ -Iehclib/base/include/ -Iehclib/array/include/ -Iehclib/filepath/include/ -Iehclib/old-locale/include/ -Iehclib/old-time/include/ -Iehclib/unix/include/ -Iehclib/directory/include/ -Iehclib/random/include/ \
        -Iinstall/101/lib/pkg/uhcbase-1.1.9.5/101/bc/plain/include -Iinstall/101/lib/pkg/base-3.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/array-1.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/filepath-1.1.0.4/101/bc/plain/include -Iinstall/101/lib/pkg/old-locale-1.0.0.2/101/bc/plain/include -Iinstall/101/lib/pkg/old-time-1.0.0.4/101/bc/plain/include -Iinstall/101/lib/pkg/unix-1.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/directory-1.0.0.0/101/bc/plain/include -Iinstall/101/lib/pkg/random-1.0.0.2/101/bc/plain/include \
	  -o build/101/ehclib/base/System/CPUTime_hsc_make \
	  build/101/ehclib/base/System/CPUTime_hsc_make.c \
   && build/101/ehclib/base/System/CPUTime_hsc_make > build/101/ehclib/base/System/CPUTime.hs \
   && rm -f build/101/ehclib/base/System/CPUTime_hsc_make.c ; \
fi \
&& touch build/101/ehclib/base/System/CPUTime.hs
/bin/sh: 4: Syntax error: redirection unexpected
ehclib/files2.mk:361: recipe for target 'build/101/ehclib/base/System/CPUTime.hs' failed
make[2]: *** [build/101/ehclib/base/System/CPUTime.hs] Error 2
make[2]: Leaving directory '/tmp/uhc-master/EHC'
ehclib/files2.mk:282: recipe for target 'install/101/lib/pkg/base-3.0.0.0/101/bc/plain/CompileAll' failed
make[1]: *** [install/101/lib/pkg/base-3.0.0.0/101/bc/plain/CompileAll] Error 2
make[1]: Leaving directory '/tmp/uhc-master/EHC'
ehclib/files2.mk:279: recipe for target '101/ehclibs' failed
make: *** [101/ehclibs] Error 2
```

It seems that the second argument to grep (line 2) is empty, which I presume it shouldn't be.

**Comment by atzedijkstra** [comment] 2016-08-21 18:26
I cannot reproduce this error. On my system (MacOSX) line 2 is indeed different:

	if grep -q 'HSC2HS_EXTRA' /usr/local/bin/hsc2hs ;\

The part empty on your system should be determined by ./configure, which then should have complained about it.

**Comment by atzedijkstra** [comment] 2016-08-21 18:30
I saw in issue #83 the path is correct, so I'll close this one.

**Closed by atzedijkstra** 2016-08-21 18:30 UTC
